import { format } from "date-fns";
import { utcToZonedTime } from "date-fns-tz";
const currentDate = utcToZonedTime(new Date(), "Australia/Sydney");
export const themeShop = [
  {
    url: "https://themeforest.net/item/minimog-the-high-converting-ecommerce-wordpress-theme/36947163",
    themeId: 36947163,
    name: "MinimogWP",
    fixedSales: 146,
    created_at: format(currentDate, "MM/dd/yyyy"),
  },
  {
    url: "https://themeforest.net/item/flatsome-multipurpose-responsive-woocommerce-theme/5484319",
    themeId: 5484319,
    name: "Flatsome",
    fixedSales: 190129,
    created_at: format(currentDate, "MM/dd/yyyy"),
  },
  {
    url: "https://themeforest.net/item/woodmart-woocommerce-wordpress-theme/20264492",
    themeId: 20264492,
    name: "WoodMart",
    fixedSales: 42550,
    created_at: format(currentDate, "MM/dd/yyyy"),
  },
  {
    url: "https://themeforest.net/item/porto-responsive-wordpress-ecommerce-theme/9207399",
    themeId: 9207399,
    name: "Porto",
    fixedSales: 72559,
    created_at: format(currentDate, "MM/dd/yyyy"),
  },
  {
    url: "https://themeforest.net/item/xstore-responsive-woocommerce-theme/15780546",
    themeId: 15780546,
    name: "XStore",
    fixedSales: 31250,
    created_at: format(currentDate, "MM/dd/yyyy"),
  },
  {
    url: "https://themeforest.net/item/razzi-woocommerce-wordpress-theme/31833761",
    themeId: 31833761,
    name: "Razzi",
    fixedSales: 2577,
    created_at: format(currentDate, "MM/dd/yyyy"),
  },
  {
    url: "https://themeforest.net/item/agrofood-elementor-woocommerce-wordpress-theme/35811586",
    themeId: 35811586,
    name: "Agrofood",
    fixedSales: 186,
    created_at: format(currentDate, "MM/dd/yyyy"),
  },
  {
    url: "https://themeforest.net/item/goya-modern-woocommerce-theme/25175097",
    themeId: 25175097,
    name: "Goya",
    fixedSales: 7020,
    created_at: format(currentDate, "MM/dd/yyyy"),
  },
  {
    url: "https://themeforest.net/item/kalles-versatile-woocommerce-theme/34529223",
    themeId: 34529223,
    name: "Kalles",
    fixedSales: 579,
    created_at: format(currentDate, "MM/dd/yyyy"),
  },
  {
    url: "https://themeforest.net/item/electro-electronics-store-woocommerce-theme/15720624",
    themeId: 15720624,
    name: "Electro",
    fixedSales: 21106,
    created_at: format(currentDate, "MM/dd/yyyy"),
  },
  {
    url: "https://themeforest.net/item/rey-multipurpose-woocommerce-theme/24689383",
    themeId: 24689383,
    name: "Rey",
    fixedSales: 4998,
    created_at: format(currentDate, "MM/dd/yyyy"),
  },
  {
    url: "https://themeforest.net/item/bookory-book-store-woocommerce-theme/36448131",
    themeId: 36448131,
    name: "Bookory",
    fixedSales: 100,
    created_at: format(currentDate, "MM/dd/yyyy"),
  },
  {
    url: "https://themeforest.net/item/elessi-woocommerce-ajax-wordpress-theme/20968615",
    themeId: 20968615,
    name: "Elessi",
    fixedSales: 4292,
    created_at: format(currentDate, "MM/dd/yyyy"),
  },
  {
    url: "https://themeforest.net/item/savoy-minimalist-ajax-woocommerce-theme/12537825",
    themeId: 12537825,
    name: "Savoy",
    fixedSales: 12897,
    created_at: format(currentDate, "MM/dd/yyyy"),
  },
  {
    url: "https://themeforest.net/item/mydecor-elementor-woocommerce-wordpress-theme/36063191",
    themeId: 36063191,
    name: "MyDecor",
    fixedSales: 183,
    created_at: format(currentDate, "MM/dd/yyyy"),
  },
  {
    url: "https://themeforest.net/item/machic-electronics-store-woocommerce-theme/34267600",
    themeId: 34267600,
    name: "Machic",
    fixedSales: 707,
    created_at: format(currentDate, "MM/dd/yyyy"),
  },
  {
    url: "https://themeforest.net/item/sober-woocommerce-wordpress-theme/18332889",
    themeId: 18332889,
    name: "Sober",
    fixedSales: 8395,
    created_at: format(currentDate, "MM/dd/yyyy"),
  },
  {
    url: "https://themeforest.net/item/ekommart-allinone-ecommerce-wordpress-theme/25893445",
    themeId: 25893445,
    name: "ekommart",
    fixedSales: 3744,
    created_at: format(currentDate, "MM/dd/yyyy"),
  },
  {
    url: "https://themeforest.net/item/bacola-grocery-store-and-food-ecommerce-theme/32552148",
    themeId: 32552148,
    name: "Bacola",
    fixedSales: 1437,
    created_at: format(currentDate, "MM/dd/yyyy"),
  },
  {
    url: "https://themeforest.net/item/martfury-woocommerce-marketplace-wordpress-theme/21273233",
    themeId: 21273233,
    name: "Martfury",
    fixedSales: 11843,
    created_at: format(currentDate, "MM/dd/yyyy"),
  }
];
