export const themeChart = [
  {
    label: "MinimogWP",
    fill: false,
    borderColor: "#ED2B33FF",
    tension: 0.3,
    url: "https://themeforest.net/item/minimog-the-high-converting-ecommerce-wordpress-theme/36947163",
  },
  {
    label: "Flatsome",
    fill: false,
    borderColor: "#A01855FF",
    tension: 0.3,
    url: "https://themeforest.net/item/flatsome-multipurpose-responsive-woocommerce-theme/5484319",
  },
  {
    label: "WoodMart",
    fill: false,
    borderColor: "#2C5F2D",
    tension: 0.3,
    url: "https://themeforest.net/item/woodmart-woocommerce-wordpress-theme/20264492",
  },
  {
    label: "Porto",
    fill: false,
    borderColor: "#5B84B1FF",
    tension: 0.3,
    url: "https://themeforest.net/item/porto-responsive-wordpress-ecommerce-theme/9207399",
  },
  {
    label: "XStore",
    fill: false,
    borderColor: "#5F4B8BFF",
    tension: 0.3,
    url: "https://themeforest.net/item/xstore-responsive-woocommerce-theme/15780546",
  },
  {
    label: "Razzi",
    fill: false,
    borderColor: "#A07855FF",
    tension: 0.3,
    url: "https://themeforest.net/item/razzi-woocommerce-wordpress-theme/31833761",
  },
  {
    label: "Agrofood",
    fill: false,
    borderColor: "#101820FF",
    tension: 0.3,
    url: "https://themeforest.net/item/agrofood-elementor-woocommerce-wordpress-theme/35811586",
  },
  {
    label: "Goya",
    fill: false,
    borderColor: "#FF6600",
    tension: 0.3,
    url: "https://themeforest.net/item/goya-modern-woocommerce-theme/25175097",
  },
  {
    label: "Kalles",
    fill: false,
    borderColor: "#00EE00",
    tension: 0.3,
    url: "https://themeforest.net/item/kalles-versatile-woocommerce-theme/34529223",
  },
  {
    label: "Electro",
    fill: false,
    borderColor: "#FFFF00",
    tension: 0.3,
    url: "https://themeforest.net/item/electro-electronics-store-woocommerce-theme/15720624",
  },
  {
    label: "Rey",
    fill: false,
    borderColor: "#FFCCFF",
    tension: 0.3,
    url: "https://themeforest.net/item/rey-multipurpose-woocommerce-theme/24689383",
  },
  {
    label: "Bookory",
    fill: false,
    borderColor: "#CC99FF",
    tension: 0.3,
    url: "https://themeforest.net/item/bookory-book-store-woocommerce-theme/36448131",
  },
  {
    label: "Elessi",
    fill: false,
    borderColor: "#6699FF",
    tension: 0.3,
    url: "https://themeforest.net/item/elessi-woocommerce-ajax-wordpress-theme/20968615",
  },
  {
    label: "Savoy",
    fill: false,
    borderColor: "#006699",
    tension: 0.3,
    url: "https://themeforest.net/item/savoy-minimalist-ajax-woocommerce-theme/12537825",
  },
  {
    label: "MyDecor",
    fill: false,
    borderColor: "#99FF33",
    tension: 0.3,
    url: "https://themeforest.net/item/mydecor-elementor-woocommerce-wordpress-theme/36063191",
  },
  {
    label: "Machic",
    fill: false,
    borderColor: "#550000",
    tension: 0.3,
    url: "https://themeforest.net/item/machic-electronics-store-woocommerce-theme/34267600",
  },
  {
    label: "Sober",
    fill: false,
    borderColor: "#666699",
    tension: 0.3,
    url: "https://themeforest.net/item/sober-woocommerce-wordpress-theme/18332889",
  },
  {
    label: "ekommart",
    fill: false,
    borderColor: "#003333",
    tension: 0.3,
    url: "https://themeforest.net/item/ekommart-allinone-ecommerce-wordpress-theme/25893445",
  },
  {
    label: "Bacola",
    fill: false,
    borderColor: "#002200",
    tension: 0.3,
    url: "https://themeforest.net/item/bacola-grocery-store-and-food-ecommerce-theme/32552148",
  },
  {
    label: "Martfury",
    fill: false,
    borderColor: "#333333",
    tension: 0.3,
    url: "https://themeforest.net/item/martfury-woocommerce-marketplace-wordpress-theme/21273233",
  }
];
